#define CHUNK_SIZE_XZ 16
#define CHUNK_SIZE_Y 128
// #define CHUNK_RENDERING_DISTANCE 6
// #define CHUNK_RENDERING_DISTANCE_IN_BLOCKS (CHUNK_RENDERING_DISTANCE * CHUNK_SIZE_XZ)
#define BAKING_CHUNK_THREADS_LIMIT 1