name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Get dependencies
        run: |
          sudo apt-get install build-essential git make
          sudo apt-get install pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev
          sudo apt-get install libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev
          sudo apt-get install libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev
          sudo apt-get install libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev
          sudo apt-get install libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Package Artifacts
        run: |
          mkdir -p ${{github.workspace}}/artifact
          cp -r ${{github.workspace}}/Assets ${{github.workspace}}/artifact/
          cp -r ${{github.workspace}}/build/crafteria ${{github.workspace}}/artifact/
          tar -czvf crafteria-linux-x86_64-${{ github.sha }}.tar.gz -C ${{github.workspace}}/artifact .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: crafteria-linux-x86_64-${{ github.sha }}.tar.gz
